server:

  port: 8980
  context-path: /js
  tomcat:
    uri-encoding: UTF-8

spring:

  profiles:
    active: default
    
  main:
    banner-mode: "off"
    
# 产品或项目名称、版本、版权年份
productName: JeeSite Demo
productVersion: V4.0
copyrightYear: 2018

# 软件提供商公司或个人名称
companyName: sharp

# 数据库连接
jdbc: 
  # Mysql 数据库配置
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/sharp?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
  username: root
  password: 12345678
  testSql: SELECT 1
